#!/bin/bash

# Run this script once a day from cron to produce up to date
# downloadable malaga vocabulary files.

# URLs and dump directories
JOUKAHAINEN_URL=http://localhost/joukahainen
VOC_DUMP_DIR=/tmp/d/voc
DB_DUMP_DIR=/tmp/d/db

# Special vocabularies
AID[0]=15
ANAME[0]=atk
AID[1]=19
ANAME[1]=kasvatustiede
AID[2]=33
ANAME[2]=laaketiede
AID[3]=35
ANAME[3]=vieraskieliset
AID[4]=36
ANAME[4]=matluonnontiede


DATE=`date +%Y-%m-%d`

wget -q "$JOUKAHAINEN_URL/malaga/default" -O "$VOC_DUMP_DIR/joukahainen-$DATE.lex"
rm "$VOC_DUMP_DIR/joukahainen.lex"
ln -s "$VOC_DUMP_DIR/joukahainen-$DATE.lex" "$VOC_DUMP_DIR/joukahainen.lex"

i="0"
while [ $i -lt ${#AID[*]} ] ; do
  wget -q "$JOUKAHAINEN_URL/malaga/special?aid=${AID[$i]}" -O "$VOC_DUMP_DIR/${ANAME[$i]}-$DATE.lex"
  rm "$VOC_DUMP_DIR/${ANAME[$i]}.lex"
  ln -s "$VOC_DUMP_DIR/${ANAME[$i]}-$DATE.lex" "$VOC_DUMP_DIR/${ANAME[$i]}.lex"
  i=$[$i+1]
done

pg_dump -F c joukahainen > "$DB_DUMP_DIR/joukahainen-$DATE.pgdump"
rm "$DB_DUMP_DIR/joukahainen.pgdump"
ln -s "$DB_DUMP_DIR/joukahainen-$DATE.pgdump" "$DB_DUMP_DIR/joukahainen.pgdump"

